# ./docker-compose.yml

version: '3'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.6.16
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - ./data:/usr/share/elasticsearch/data
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
      nproc:
        soft: 2048
        hard: 2048
    #expose this for local dev only!
    #ports:
    #  - "9200:9200"
  redis:
    build:
      context: ./redis-docker
    #expose this for local dev only!
    #ports:
    #  - "6379:6379"
  kibana:
    image: docker.elastic.co/kibana/kibana:5.6.16
    depends_on:
      - elasticsearch
    ports:
      - "5601:5601"
  python3:
    build:
      context: ./python-docker
    depends_on:
      - elasticsearch
      - redis
    volumes:
      - ./src:/usr/src/app
